---
title: "Problem 2 - New York weather dashboard"
output: 
  flexdashboard::flex_dashboard:
    toc: true
    orientation: columns
    vertical_layout: fill
---

#### to knit dashboard within website, either build the whole website, or be specific in what gets knitted:
rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(viridis)
library(plotly)
library(p8105.datasets)


data(ny_noaa)
set.seed(1)
ny_noaa = sample_n(ny_noaa, 1000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Seasonal variation in New York temperature by year

```{r}
plot_data = ny_noaa %>% 
  mutate(year = year(date),
         month = month(date),
         season = case_when(
           month %in% c(3, 4, 5) ~ "spring",
           month %in% c(6, 7, 8) ~ "summer",
           month %in% c(9, 10, 11) ~ "fall",
           month %in% c(12, 1, 2) ~ "winter"
         ) %>% factor(levels = c("spring", "summer", "fall", "winter")),
         tmax = as.numeric(tmax),
         tmin = as.numeric(tmin)) %>% 
  group_by(year, season) %>% 
  mutate(mean_tmax = mean(tmax, na.rm = TRUE)) %>% 
  ungroup() %>% 
  arrange(year, season)

plot_data %>%
  plot_ly(
    x = ~year, y = ~mean_tmax, type = "scatter", mode = "lines+markers",
    color = ~season, text = ~tmax, alpha = 0.5) %>% 
  layout(title = "Mean maximum temperature in NY by year and season",
         xaxis = list(title = "year"),
         yaxis = list(title = "maximum temperature (tenths of degrees C)"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### New York precipitation by season

```{r}
plot_data %>% 
  plot_ly(y = ~prcp, 
          color = ~season, 
          type = "violin", 
          box = list(
            visible = T
          ),
          colors = "Set2") %>% 
  layout(title = "Seasonal variation in NY precipitation",
         xaxis = list(title = "season"),
         yaxis = list(title = "precipitation (tenths of mm)"))
```

### Yearly New York snowfall

```{r}
plot_data %>% 
  group_by(year) %>% 
  summarize(sum_snow = sum(snow, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(year = factor(year)) %>% 
  plot_ly(x = ~year, y = ~sum_snow, color = ~year, type = "bar") %>% 
  layout(title = "Total snowfall in NY by year",
         xaxis = list(title = "year"),
         yaxis = list(title = "total snowfall (mm)"),
         showlegend = FALSE)
```

